RecruitmentTracking/Models/Candidate/Candidate.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RecruitmentTracking.Models;

public class Candidate
{
    [Key]
    public int CandidateId { get; set; }
    public string? Phone { get; set; }
    public double GPA { get; set; }
    public string? LastEducation { get; set; }

    public string? Schedule { get; set; }
    public string? Salary { get; set; }

    [ForeignKey("User")]
    public string? UserId { get; set; }
    public User? User { get; set; }
}

RecruitmentTracking/Models/Job/EmailTemplate.cs
namespace RecruitmentTracking.Models;

public class EmailTemplate
{
    public int JobId { get; set; }
    public string? EmailHR { get; set; }
    public string? EmailUser { get; set; }
    public string? EmailOffering { get; set; }
    public string? EmailReject { get; set; }
}

RecruitmentTracking/Models/Job/Job.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RecruitmentTracking.Models;

public class Job
{
    [Key]
    public int JobId { get; set; }
    [Required]
    public string? JobTitle { get; set; }
    [Required]
    public string? JobDescription { get; set; }
    [Required]
    public string? JobRequirement { get; set; }
    [Required]
    public bool IsJobAvailable { get; set; }
    [Required]
    public string? Location { get; set; }

    [Required]
    [DataType(DataType.Date)]
    public DateTime? JobPostedDate { get; set; }
    [Required]
    [DataType(DataType.Date)]
    public DateTime? JobExpiredDate { get; set; }

    public int candidateCount { get; set; }

    public string? ProcessStatus { get; set; }

    public string? EmailHR { get; set; }
    public string? EmailUser { get; set; }
    public string? EmailOffering { get; set; }
    public string? EmailReject { get; set; }


    public string? UserEmailInterview { get; set; }

    [ForeignKey("User")]
    public string? AdminId { get; set; }
    public User? User { get; set; }
}

RecruitmentTracking/Models/Job/JobCreate.cs
using System.ComponentModel.DataAnnotations;

namespace RecruitmentTracking.Models;

public class JobCreate
{
    public int JobId { get; set; }
    [Required(ErrorMessage = "Please fill in the required information.")]

    public string? JobTitle { get; set; }
    [Required(ErrorMessage = "Please fill in the required information.")]

    public string? JobDescription { get; set; }
    [Required(ErrorMessage = "Please fill in the required information.")]

    public string? JobRequirement { get; set; }
    public bool IsJobAvailable { get; set; }
    [Required(ErrorMessage = "Please fill in the required information.")]

    public string? Location { get; set; }
    public DateTime? JobExpiredDate { get; set; }

}

RecruitmentTracking/Models/Job/JobData.cs
namespace RecruitmentTracking.Models;

public class JobData
{
    public int JobId { get; set; }
    public string? JobTitle { get; set; }
    public string? JobDescription { get; set; }
    public string? JobRequirement { get; set; }
    public string? Location { get; set; }
    public DateTime? JobPostedDate { get; set; }
    public DateTime? JobExpiredDate { get; set; }

    public int CandidateCout { get; set; }
}

RecruitmentTracking/Models/Job/JobModelView.cs
namespace RecruitmentTracking.Models;

public class JobViewModel
{
    public int JobId { get; set; }
    public string? JobTitle { get; set; }
    public string? JobDescription { get; set; }
    public string? JobRequirement { get; set; }
    public string? Location { get; set; }
    public DateTime? JobPostedDate { get; set; }
    public DateTime? JobExpiredDate { get; set; }

    public int CandidateCout { get; set; }
}

RecruitmentTracking/Controllers/CandidateController.cs
using Microsoft.AspNetCore.Mvc;

using RecruitmentTracking.Models;
using RecruitmentTracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace RecruitmentTracking.Controllers;

[Authorize]
public class CandidateController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<HomeController> _logger;
    private readonly IConfiguration _configuration;
    private readonly IWebHostEnvironment _server;
    private readonly UserManager<User> _userManager;

    public CandidateController(ILogger<HomeController> logger, IWebHostEnvironment server, IConfiguration configuration, ApplicationDbContext context, UserManager<User> userManager)
    {
        _logger = logger;
        _server = server;
        _configuration = configuration;
        _context = context;
        _userManager = userManager;
    }

    [HttpGet("/Profile")]
    public async Task<IActionResult> Profile()
    {
        User user = (await _userManager.GetUserAsync(User))!;

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        Candidate objCandidate = (await _context.Candidates!.FirstOrDefaultAsync(c => c.UserId == user.Id))!;

        if (objCandidate == null)
        {
            Candidate newCandidate = new()
            {
                User = user,
            };
            _context.Candidates?.Add(newCandidate);
            await _context.SaveChangesAsync();

            UserEditProfile newProfile = new UserEditProfile()
            {
                Name = user.Name,
                Email = user.Name,
                Phone = newCandidate.Phone,
                LastEducation = newCandidate.LastEducation,
                GPA = newCandidate.GPA,
            };

            return View(newProfile);
        }

        UserEditProfile profile = new UserEditProfile()
        {
            Name = user.Name,
            Phone = objCandidate.Phone,
            LastEducation = objCandidate.LastEducation,
            GPA = objCandidate.GPA,
        };

        return View(profile);
    }

    [HttpPost("/EditProfile")]
    public async Task<IActionResult> EditProfile(UserEditProfile profile)
    {
        User user = (await _userManager.GetUserAsync(User))!;

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        Candidate candidate = (await _context.Candidates!.FirstOrDefaultAsync(c => c.UserId == user.Id))!;
        user.Name = profile.Name;
        candidate.Phone = profile.Phone;
        candidate.LastEducation = profile.LastEducation;
        candidate.GPA = profile.GPA;

        await _context.SaveChangesAsync();

        TempData["success"] = "Successfully Update Profile";
        return Redirect("/");
    }


    [HttpGet("/Home/ApplyJob/{id}")]
    public async Task<IActionResult> ApplyJob(int id)
    {
        User user = (await _userManager.GetUserAsync(User))!;

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        Job objJob = (await _context.Jobs!.FindAsync(id))!;

        ViewBag.JobId = id;

        Candidate objCandidate = _context.Candidates!.FirstOrDefault(c => c.UserId == user.Id)!;

        UserEditProfile data = new()
        {
            Name = user.Name,
            Phone = objCandidate.Phone,
            LastEducation = objCandidate.LastEducation,
            GPA = objCandidate.GPA,
        };

        return View(data);
    }

    [HttpPost]
    public async Task<IActionResult> ApplyJobs(int JobId, UserEditProfile updateCandidate)
    {

        if (updateCandidate.FileCV?.Length < 0)
        {
            TempData["warning"] = "Please select a CV file";
            return Redirect($"/Home/ApplyJob/{JobId}");
        }

        User user = (await _userManager.GetUserAsync(User))!;

        UserJob UJ = (await _context.UserJobs!.FirstOrDefaultAsync(cj => cj.JobId == JobId && cj.UserId == user.Id))!;
        if (UJ != null)
        {
            TempData["error"] = "You have applied for the job";
            return Redirect($"/Home/ApplyJob/{JobId}");
        }

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(updateCandidate.FileCV!.FileName);

        string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "Data", "DataCV");

        Directory.CreateDirectory(uploadsFolder);

        string filePath = Path.Combine(uploadsFolder, fileName);

        Candidate objCandidate = (await _context.Candidates!.FirstOrDefaultAsync(c => c.UserId == user.Id))!;
        user.Name = updateCandidate.Name;
        objCandidate.Phone = updateCandidate.Phone;
        objCandidate.LastEducation = updateCandidate.LastEducation;
        objCandidate.GPA = updateCandidate.GPA;

        Job objJob = (await _context.Jobs!.FindAsync(JobId))!;

        UserJob objCJ = new()
        {
            UserId = user.Id,
            Job = objJob,
            CV = fileName,
            StatusInJob = $"{ProcessType.Administration}",
        };

        objJob.candidateCount++;
        await _context.UserJobs!.AddAsync(objCJ);
        await _context.SaveChangesAsync();

        using (var stream = new FileStream(filePath, FileMode.Create))
        {
            updateCandidate.FileCV.CopyTo(stream);
        }

        TempData["success"] = "Application Successfully Sent";
        return Redirect("/TrackJob");
    }

    [HttpGet("/TrackJob")]
    public async Task<IActionResult> TrackJob()
    {
        User user = (await _userManager.GetUserAsync(User))!;

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        List<Job> listJobCandidate = _context.UserJobs!
                            .Where(c => c.UserId == user.Id)!
                            .Select(c => c.Job)
                            .ToList()!;

        List<CandidateJobStatus> listData = new();
        foreach (Job job in listJobCandidate)
        {
            UserJob UJ = (await _context.UserJobs!.FirstOrDefaultAsync(cj => cj.JobId == job.JobId && cj.UserId == user.Id))!;
            CandidateJobStatus status = new()
            {
                CandidateStatus = GetStatusApplication(UJ.StatusInJob!).Split(' '), // need migrate db to CandidateJobStatus for status in Job
                JobTitle = job.JobTitle,
            };
            listData.Add(status);
        }
        return View(listData);
    }

    [HttpGet("/Jobs")]
    public async Task<IEnumerable<Job>> Job()
    {
        return await _context.Jobs!.Where(Job => Job.IsJobAvailable).ToListAsync();
    }

    [HttpPatch("/EditProfile")]
    public async Task<IActionResult> EditProfile(Candidate objCandidate)
    {
        _context.Entry(objCandidate).State = EntityState.Modified;
        await _context.SaveChangesAsync();

        return Ok(objCandidate);
    }

    private string GetStatusApplication(string status)
    {
        List<string> process = new()
        {
            "current-item none none none",
            "none current-item none none",
            "none none current-item none",
            "none none none current-item",
        };

        int step = (int)Enum.Parse(typeof(ProcessType), status);

        if (step == 7) return "Rejected";

        return process[step - 1];
    }
}

RecruitmentTracking/Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace RecruitmentTracking.Controllers;

public class JobController : Controller
{
	
}

RecruitmentTracking/Views/Candidate/ApplyJob.cshtml
@model UserEditProfile

@{
    ViewData["Title"] = "Apply Job";
    var dropdownOptions = new List<SelectListItem>
    {
        new SelectListItem { Value = "Doctorate", Text = "Doctorate" },
        new SelectListItem { Value = "Master's Degree", Text = "Master's Degree" },
        new SelectListItem { Value = "Bachelor's Degree", Text = "Bachelor's Degree" },
        new SelectListItem { Value = "Diploma", Text = "Diploma" },
        new SelectListItem { Value = "SMA/SMK", Text = "SMA/SMK"}
    };
}

          <!-- content for apply job form -->
           <div class="pt-5 pb-20 px-5">
            
            <div class="container shadow p-3 mb-5 bg-white rounded mt-5" style="background-color:#f8f9fa ">
              <p class="text-xl">Apply Job :</p>
            
              <p class="text-3xl font-bold mb-3 mt-3">@ViewBag.JobTitle</p>
            <hr/>
              @using(Html.BeginForm("ApplyJobs", "Candidate", FormMethod.Post, new { enctype = "multipart/form-data"}))
              {
                 <input type="hidden" name="JobId" value="@ViewBag.JobId" />

                <div class="mt-5">
                    <label for="name" class="form-label">Full Name</label>
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control"})
              
                    <label for="phone" class="form-label">Phone Number</label>
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", type = "number" })
                
                    <label for="education" class="form-label text-muted mt-2">Last Education</label>
                    @Html.DropDownListFor(m => m.LastEducation, new SelectList(dropdownOptions, "Value", "Text"), "Select an option", new { @class = "form-control round-lg" })
               
                   <label for="GPA" class="form-label">GPA</label>
                    @Html.TextBoxFor(m => m.GPA, new { @class = "form-control rounded-lg", type = "number", step = "0.01", min = "0", max = "4" })

                    <label for="phone" class="form-label">Expectation Salary</label>
                    @Html.TextBoxFor(m => m.Salary, new { @class = "form-control", type = "number" })

                @* <label for="file" class="form-label mt-3">Upload CV/Resume</label>
                  @Html.TextBoxFor(m => m.FileCV, new { @class = "form-control" ,@type = "file"}) *@
                <label for="file" class="form-label mt-3">Upload CV/Resume (PDF, maks. 1MB)</label>
                @Html.TextBoxFor(m => m.FileCV, new { @class = "form-control", @type = "file", @id = "file-input", @required = "required" })
                @* <input type="file" class="form-control" id="file" name="file"> *@
                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
                  <button type="submit" class="btn bg-amber-500 text-white rounded-lg hover:bg-amber-600">Submit</button>
                </div>
                    
                </div>
              }
            </div>
          </div>
    
<script>
  // Ambil elemen input file
  var fileInput = document.getElementById("file-input");

  // Tambahkan event listener untuk memvalidasi file saat dipilih
  fileInput.addEventListener("change", function() {
    var file = fileInput.files[0]; // Ambil file yang dipilih
    var maxSize = 1048576; // Ukuran maksimal file dalam byte (1 MB = 1,048,576 bytes)

    // Validasi format file
    var fileType = file.type.toLowerCase();
    if (fileType !== "application/pdf") {
      alert("Mohon pilih file dalam format PDF.");
      fileInput.value = ""; // Reset nilai input file
      return;
    }

    // Validasi ukuran file
    if (file.size > maxSize) {
      alert("Ukuran file terlalu besar. Maksimal 1MB.");
      fileInput.value = ""; // Reset nilai input file
      return;
    }
  });
</script>

RecruitmentTracking/Views/Candidate/Jobs.cshtml
@{
    ViewData["Title"] = "Jobs";
}

     <!-- search bar -->
   <div class="pt-32 pb-20 px-5 bg-custom-background">
      <div class="w-full container flex justify-between space-y-3 flex-col lg:space-x-3 lg:space-y-0 lg:flex-row">
        <div class="w-full">
          <input type="text" class="form-control  rounded-lg" placeholder="Search Job" aria-label="City" />
        </div>
        <div class="dropdown w-1/3">
          <select class="form-select" aria-label="Default select example">
            <option selected>Choose location</option>
            <option value="Bandung">Bandung</option>
            <option value="Salatiga">Salatiga</option>
            <option value="Semarang">Semarang</option>
          </select>
        </div>
        <button type="button" class="w-1/3 btn bg-amber-500 text-white hover:bg-amber-600 rounded-lg">Search<i
            class="bi bi-search mx-2"></i></i></button>
      </div>
    </div>

    <!-- job list -->
    <div class="container mb-3">
      <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
        @foreach (var job in Model){
        <div class="col">
          <div class="card h-[350px] w-full">
            <div class="card-header">
              <h5 class="font-medium text-xl">@job.JobTitle</h5>
                <span class="text-gray-600 flex items-center space-x-1">
                <i class="bi bi-geo-alt"></i>
                <h7 class="card-text  text-sm">Location: @job.Location</h7>
              </span>
              </div>
              <div class="card-body flex flex-column justify-between">
              @* <h6>Employee count: @job.CandidateCout</h6> *@
              <div class="card-text">
                <p class="line-clamp-5"> @job.JobDescription</p>
              </div>
              <div class="flex justify-end mt-3 space-x-2">
                @* @if(User.Identity.IsAuthenticated)
                { *@
                  <a type="button" class="btn bg-amber-500 text-white rounded-lg hover:bg-amber-600" href="@Url.Action("ApplyJob", new { id =job.JobId })">Apply</a>
                @* }
                else
                {
                  <a type="button" class="btn btn-primary" href="/Login">Apply</a>
                } *@
                <a type="button" class="btn border-2 border-amber-500 text-amber-500 rounded-lg hover:bg-amber-500 hover:text-white" href="@Url.Action("DetailJob", new { id = job.JobId })" >Details</a>
              </div>
            </div>
            <div class="card-footer text-muted">
            <div class="flex justify-between">
              <span class="flex space-x-1 items-center">
                <i class="bi bi-person-plus"></i>
                <h7 class="card-text">Due Date : </h7>
              </span>
              <span class="flex space-x-1 items-center">
                <i class="bi bi-person"></i>
                <h7 class="card-text">Total Applicant : @job.CandidateCout</h7>
              </span>
            </div>
            <div class="mt-2">
              <i class="bi bi-clock"></i>
              <h7 class="card-text">Posted Time</h7>
            </div>
          </div>
          </div>
        </div>
        }
      </div>
    </div>

RecruitmentTracking/Views/Candidate/Profile.cshtml
@model UserEditProfile

@{
    ViewData["Title"] = "Edit Profile";
    var dropdownOptions = new List<SelectListItem>
    {
        new SelectListItem { Value = "Doctorate", Text = "Doctorate" },
        new SelectListItem { Value = "Master's Degree", Text = "Master's Degree" },
        new SelectListItem { Value = "Bachelor's Degree", Text = "Bachelor's Degree" },
        new SelectListItem { Value = "Diploma", Text = "Diploma" },
        new SelectListItem { Value = "SMA/SMK", Text = "SMA/SMK"}
    };
}

          <!-- content for edit profile -->
          <div class="pt-5 pb-20 px-5">
            <div class="container shadow p-3 mb-5 bg-white rounded mt-5" style="background-color:#f8f9fa ">
            @using(Html.BeginForm("EditProfile", "Candidate", FormMethod.Post))
            {
                <div class="mt-2">
                    <label for="Name" class="form-label text-muted">Name</label>
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control rounded-lg"})
                </div>
                @* <div class="mt-2">
                    <label for="email" class="form-label text-muted">Email address</label>
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control rounded-lg", @readonly = "readonly" })
                </div> *@

                <div class="mt-2">
                    <label for="phone" class="form-label text-muted">Phone Number</label>
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control rounded-lg", type="number"})
                </div>
                <div class="mt-2">
                    <label for="education" class="form-label text-muted">Last Education</label>
                    @Html.DropDownListFor(m => m.LastEducation, new SelectList(dropdownOptions, "Value", "Text"), "Select an option", new { @class = "form-control round-lg" })
                </div>
                <div class="mt-2">
                    <label for="GPA" class="form-label text-muted">GPA</label>
                    @Html.TextBoxFor(m => m.GPA, new { @class = "form-control rounded-lg", type = "number", step = "0.01", min = "0", max = "4" })
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-5">
                    <button class=" w-1/3 btn bg-amber-500 text-white rounded-lg hover:bg-amber-600" type="submit">Save</button>
                </div>
            }
            </div>
          
          </div>

RecruitmentTracking/Views/Candidate/TrackJob.cshtml
@model List<CandidateJobStatus>

@{
    ViewData["Title"] = "My Application";

    
} 
  <div class="pt-32 pb-20 px-5 ">
    <div class="container"  ">
      <p class="font-bold text-2xl">My Application Status :</p>

      @foreach (var status in Model)
      {
        @if (status.CandidateStatus![0] == "Rejected")
        {
            <div class="container mt-3" style="background: #fff;
    box-shadow: 0 15px 25px rgba(0,0,0,0.1);">
                <a class="step-wizard-list d-flex">
                    <div class="">
                        <p class="text-2xl font-bold fw-smedium ms-3">@status.JobTitle</p>
                        <p class="text-base font-bold fw-medium mt-2 ms-3 text-red-400"><i class="bi bi-x-circle mr-2"></i>Not Suitable</p>
                        <p class="text-sm font-bold  text-muted fw-medium mt-2 ms-3">We sincerely appreciate your interest in joining our team and value the time and effort you invested in your application.<br>
                        We wish you the best of luck in your job search and future endeavors.</p>
                    </div>
                </a>
            </div>
        } else {
       
        string style_1 = status.CandidateStatus![0];
        string style_2 = status.CandidateStatus![1];
        string style_3 = status.CandidateStatus![2];
        string style_4 = status.CandidateStatus![3];
      
      <div>

            
          <section class="step-wizard mt-5"> 
            
            <div class="container" style="background: #fff;
    box-shadow: 0 15px 25px rgba(0,0,0,0.1);">
                <p class="text-2xl font-bold fw-smedium ms-3 mt-3">@status.JobTitle</p>
                <ul class="step-wizard-list d-flex justify-content-center justify-content-between">
                    <li class="step-wizard-item @style_1">
                        <span class="progress-count">1</span>
                        <span class="progress-label fw-normal">Administration</span>
                    </li>
                    <li class="step-wizard-item @style_2">
                        <span class="progress-count">2</span>
                        <span class="progress-label fw-normal">HR Interview</span>
                    </li>
                    <li class="step-wizard-item @style_3">
                        <span class="progress-count">3</span>
                        <span class="progress-label fw-normal">User Interview</span>
                    </li>
                    <li class="step-wizard-item @style_4">
                        <span class="progress-count">4</span>
                        <span class="progress-label fw-normal">Offering</span>
                    </li>
                </ul>
            </div>
        </section>
        </div>
        }
      }
    </div>
  </div>